# Generated by Django 3.2.9 on 2021-12-02 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.TextField(default=''),
        ),
    ]
