# Generated by Django 3.2.9 on 2021-12-04 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_product_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='images',
        ),
    ]
